#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-term.js
Version  : 0.0.4.2
Release  : 5
URL      : https://pypi.python.org/packages/source/X/XStatic-term.js/XStatic-term.js-0.0.4.2.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-term.js/XStatic-term.js-0.0.4.2.tar.gz
Summary  : term.js 0.0.4 (XStatic packaging standard)
Group    : Development/Tools
License  : MIT
Requires: XStatic-term.js-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-termjs
--------------
term.js javascript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-term.js package.
Group: Default

%description python
python components for the XStatic-term.js package.


%prep
%setup -q -n XStatic-term.js-0.0.4.2

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
